### PR TITLE
Duktape 1.2.1

### PR DESCRIPTION
**Pull request by josh**

### CODE REVIEW

**Comment by judofyr** [comment]
Hah, nice that I can read the Duktape diff right in here.

Anything interesting for us in this release?

**Comment by josh** [comment]
> Anything interesting for us in this release?

The regexp max callstack size was significantly bumped. Should improve compatibility with more complex regexps.

**Comment by josh** [comment]
1.2.1 was just released. Updated in this PR.

**Comment by judofyr** [comment]
Released!

**Comment by josh** [comment]
:tada:

**Pull request merged**
