### PR TITLE
Check in duktape.c

### LINKED ISSUE #22: Support Bundler git target
It'd be nice to be able to test duktape.rb from a Bundle git target.

``` ruby
gem "duktape", github: "judofyr/duktape.rb"
```

I think it doesn't work because `ext/duktape/duktape.c` and `ext/duktape/duktape.h` aren't checked in

```
duktape at /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/bundler/gems/duktape.rb-fe2d192bdb5d did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
If you need to use this package without installing it from a gem repository, please contact judofyr@gmail.com and ask them to modify their .gemspec so it can work with `gem build`.
The validation message from Rubygems was:
  ["ext/duktape/duktape.c", "ext/duktape/duktape.h"] are not files
```

I think theres a few ways to work around this if we really don't want to check these files in. Instead of the rake file downloading the files, executing the `.gemspec` would probably need to.

Any objections to just checking in the source or should I look into this alternate approach? I'll get a PR going for either, but just wanted your feedback first.

/cc @judofyr

### PR DESCRIPTION
**Pull request by josh**
Closes #22

If we decide to go this route.

### CODE REVIEW

**Comment by judofyr** [comment]
Might need to update the Rakefile as well?

**Comment by josh** [comment]
I wasn't sure how you wanted that to work. If you clobber and rerun rake it should repopulate it. Should we have some sort of explicit task that always redownloads and overrides whats locally? `rake update_duktape` or something?

**Comment by josh** [comment]
Defined an explicit `rake update_duktape` that will have to be ran along with any `version.rb` changes.

**Comment by judofyr** [comment]
Let's give it a try. In a few years we might regret it :)

**Pull request merged**
