### PR TITLE
use duktape 1.6.1: better error messages, minor fixes, performance

### PR DESCRIPTION
**Pull request by did**
hi @judofyr, I updated the duktap lib with the last known 1.x version. All the tests pass. 
btw, I also tested with the 2.0 version but it broke the compilation.
thanks!

### CODE REVIEW

**Comment by judofyr** [comment]
Looks good. I'll push a new gem release and then I'll see if I can make Duktape 2 work.

**Comment by did** [comment]
that was quick! thank you so much @judofyr!

**Comment by judofyr** [comment]
The latest master now includes Duktape 2. Can you try it on your project and see if everything works as expected? All the tests pass here.

**Comment by did** [comment]
hi @judofyr, just to confirm, tests also pass on my projects (with Duktape2).

**Comment by judofyr** [comment]
That's good. I still need to implement a correct fatal handler before the release.

**Pull request merged**
